# Formerly called: anthropic_filemap.yaml
# This template is heavily inspired by anthropic's computer use demo, but you can use
# it with any LM.
agent:
  templates:
    system_template: |-
      You are a helpful assistant that can interact with a computer to solve tasks.
      CRITICAL RULES (NEVER BREAK THESE):
      1. You MUST respond with EXACTLY ONE function call for EVERY response
      2. This includes when you're ready to submit - call submit() as a function
      3. NEVER switch to text mode or write explanations without a function call
      4. There is NO "conclusion mode" - always use function calls until the system ends the session
      5. ONLY fix the specific issue mentioned in the task
      6. Do NOT explore or fix other problems
      7. Do NOT run pytest or test suites unless explicitly instructed to do so, only run the reproduction script you created

      Never switch from Choices(finish_reason='tool_calls'...) to Choices(finish_reason='stop'...) even if you think we are close to being finished with the response. We want to always be in tool_calls mode.
      Reasoning: high
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{working_dir}}. Consider the following PR description:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      Can you help me implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met?
      Your task is to make the minimal changes to files in the {{working_dir}} directory to ensure the <pr_description> is satisfied.
      Follow these steps to resolve the issue:
      1. As a first step, it might be a good idea to find and read code relevant to the <pr_description>
      2. Create a script to reproduce the error and execute it with `python <filename.py>` using the bash tool, to confirm the error
      3. Edit the sourcecode of the repo to resolve the issue
      4. Rerun your reproduce script and confirm that the error is fixed!
      5. Think about edgecases and make sure your fix handles them as well
      Your thinking should be thorough and so it's fine if it's very long.

      SCOPE: Fix ONLY the specific issue in the PR description. Do NOT fix other issues.
      TESTING: Do NOT run pytest. Only run direct Python scripts like `python script.py`.
    next_step_template: |-
      OBSERVATION:
      {{observation}}
      (Open file: {{open_file}})
      (Current directory: {{working_dir}})
      bash-$

      Continue using function calls. Never switch to text mode.
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
      (Open file: {{open_file}})
      (Current directory: {{working_dir}})
      bash-$
    demonstration_template: |
      Here is a demonstration of how to correctly accomplish this task.
      It is included to show you how to correctly use the interface.
      You do not need to follow exactly what is done in the demonstration.
      --- DEMONSTRATION ---
      {{demonstration}}
      --- END OF DEMONSTRATION ---
    demonstrations:
      - trajectories/demonstrations/str_replace_anthropic_demo.yaml
    put_demos_in_history: true
  tools:
    env_variables:
      PAGER: cat
      MANPAGER: cat
      LESS: -R
      PIP_PROGRESS_BAR: 'off'
      TQDM_DISABLE: '1'
      GIT_PAGER: cat
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m
      - path: tools/forfeit
    registry_variables:
      USE_FILEMAP: 'true'
      SUBMIT_REVIEW_MESSAGES:
        - |
          Thank you for your work on this issue. Please carefully follow the steps below to help review your changes.

          1. If you made any changes to your code after running the reproduction script, please run the reproduction script again.
            If the reproduction script is failing, please revisit your changes and make sure they are correct.
            If you have already removed your reproduction script, please ignore this step.
          2. Remove your reproduction script (if you haven't done so already).
          3. Run the submit command again to confirm.

          Here is a list of all of your changes:

          <diff>
          {{diff}}
          </diff>
    enable_bash_tool: true
    parse_function:
      type: function_calling
  history_processors:
    - type: last_n_observations
      n: 5
